### ISSUE TITLE
Not able to run the extensions?

### ISSUE THREAD

**Issue by kangruixiang** [printfuck/xExtension-Readable#9]
Hi there. So I've never been able to make the extensions work. I have the following docker compose file:

```
name: freshrss
services:
    freshrss:
        container_name: freshrss
        ports:
            - 9009:80
        environment:
            - TZ=America/New_York
        volumes:
            - /Users/kangruixiang/Documents/docker/freshrss:/config
        restart: always
        image: ghcr.io/linuxserver/freshrss
        links:
          - read:read
          
    read:
        image: phpdockerio/readability-js-server
        restart: always
      
    merc:
        image: wangqiru/mercury-parser-api
        restart: always

    fivefilters:
        image: "heussd/fivefilters-full-text-rss:latest"
        environment:
          # Leave empty to disable admin section
          - FTR_ADMIN_PASSWORD=
        volumes:
          - /Users/kangruixiang/Documents/docker/freshrss/fivefilters:/var/www/html/cache/rss
        ports:
          - "127.0.0.1:8006:80"
        restart: always
```

On the plugin page I have other plugins. But Read and Merc are not showing up:

![Screenshot 2024-08-18 at 3 34 57 PM](https://github.com/user-attachments/assets/95cb4251-2e9f-400f-bbce-fcbca5ad9705)
